#!/usr/bin/pyhton3
def raise_exception():
    print('{}'.format('inte' + 2))
